SELECT P.FN, P.LN
FROM PROFESSOR P, COURSE C
WHERE SUBSTRING( C.SEMESTER, 1, 1 ) =  'F'
AND P.PID = C.PID
AND P.PID NOT 
IN (
SELECT P.PID
FROM PROFESSOR P, COURSE C
WHERE SUBSTRING( C.SEMESTER, 1, 1 ) =  'S'
AND P.PID = C.PID
)
