SELECT COUNT( DISTINCT S.SID ) 
FROM COURSESTAKEN CT1, COURSESTAKEN CT2, COURSE C1, COURSE C2, STUDENT S
WHERE C1.EXAMDATE = C2.EXAMDATE
AND C1.CID != C2.CID
AND CT1.CID = C1.CID
AND CT2.CID = C2.CID
AND CT1.SID = S.SID
AND CT2.SID = S.SID
