SELECT S.FN, S.LN
FROM COURSE C1, COURSE C2, STUDENT S, PROFESSOR P, COURSESTAKEN CT, COURSESTAKEN CT2
WHERE C1.NAME =  'COMP 401'
AND C2.NAME =  'COMP 426'
AND P.FN =  'Ketan'
AND P.LN =  'Mayer-Patel'
AND C1.PID = P.PID
AND C2.PID = P.PID
AND (
CT.CID = C1.CID
AND CT.SID = S.SID
)
AND (
CT2.CID = C2.CID
AND CT2.SID = S.SID
)
